version: "3"
services:
  hub:
    image: selenium/hub:3.141.59
  chrome:
    image: selenium/node-chrome:3.141.59
    shm_size: '512mb'
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  chrome:
    image: selenium/node-chrome:3.141.59
    shm_size: '512mb'
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub    
  firefox:
    image: selenium/node-firefox:3.141.59
    shm_size: '512mb'
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  firefox:
    image: selenium/node-firefox:3.141.59
    shm_size: '512mb'
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub    
  Search-module1:
    image: 00707071/selenium-docker
    depends_on:
      - chrome 
      - firefox
    environment:
      - BROWSER=chrome
      - HUB_HOST=hub 
      - MODULE=Search.xml 
    volumes:
      - ./Test_Output/searhtest-result1:/usr/share/workTest/test-output
  Search-module2:
    image: 00707071/selenium-docker
    depends_on:
      - chrome 
      - firefox
    environment:
      - BROWSER=firefox
      - HUB_HOST=hub 
      - MODULE=Search.xml 
    volumes:
      - ./Test_Output/searhtest-result2:/usr/share/workTest/test-output    
  Flight-module1:
    image: 00707071/selenium-docker
    depends_on:
      - chrome 
      - firefox
    environment:
      - BROWSER=chrome
      - HUB_HOST=hub 
      - MODULE=Flight.xml 
    volumes:
      - ./Test_Output/Flight-result1:/usr/share/workTest/test-output
  Flight-module2:
    image: 00707071/selenium-docker
    depends_on:
      - chrome 
      - firefox
    environment:
      - BROWSER=firefox
      - HUB_HOST=hub 
      - MODULE=Flight.xml 
    volumes:
      - ./Test_Output/Flight-result2:/usr/share/workTest/test-output